version: '3.8'

services:
  rtsp-streamer:
    build: .
    container_name: rtsp_web_streamer
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY
      - LOGIN:test
      - PASSWORD
      - RTSP_STREAM1
      - RTSP_STREAM2
      - RTSP_STREAM3